language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
true:
  branch: master
after_success:
- "./scripts/travis_after_success.sh"
env:
  matrix:
    secure: ZBJxPPNd+M8BmwWlZ2NhE5nvnMVydsZsHWGD2wLKH6x+AN8HtlfFx584PhKewqsm6/mEpinn09lz74uoS/uW4nwqImr74VK6dDHhAYWKANU5lO7rwORGNdMwOzTpVwxLU0UjdCPNQ9Cw4Vzy7VyGTYdRmpdzmEXCY9u4o9Az0L1BLlZTnFo4OswqXvUfXZGx+AjZq8CMdq82Lb72XyU3LRlktmtHAlK9m2jFWlFKnAGfYQ5nMnM44QNVfk51PTUIZrgy9CDVyzOzYBdzHoBQ3ElMUmuLuhmq1TAq7stE3By6kY5eLOKgrya1Is/VZ1m+fM4nQf5pZULC7JvO1ncVEUybwamWU9va8HKQ22CMuYC4KJTh+Vs08iGv7o0a1r6Dj5AjQl2wO3nt+SydNPbPk/P411Si0pkySNF9n3xszU79q9SAaWv9v0rjeX+VshSLIf/c5YBYSVloSS7alfOiXrqHvgf9OUmhxGIeXca9hFNBefCCfU1wACUkDQX5mXnat44o5JaPZsGGa9SOb0+wveGyV1tucZyt7TcoR+hXIeqJI2H5NhVs4IX+JEqrQCM/FNkvqczatB86VelHN808KERPB4g0l8xfHYLK1rdU0KHjmlpJ9z1E7OHv5sxG0kPN0JIrUdg3D5LuYjj0ZrnrUsrvXf4j1hm8O9ejb/5DMgk=
